### ISSUE TITLE
Bot down

### ISSUE THREAD

**Issue by Songlilly** [Aida-Enna/MognetPlugin#22] opened 2020-11-24 22:58 UTC
Bot has been down for over a month now, just wondering if its dead or being fixed? My FC and I really like this bot and there doesn't seem to be any other bot to replace it.

**Comment by rftr** [comment] 2020-12-16 00:28
no comments. I think we can assume dead

**Comment by Aida-Enna** [comment] 2020-12-30 00:55
For some reason this repo -really- doesn't seem to want to notify me when issues are opened, even though I've turned on all notifications for it. Someone poked me on discord and I restarted it. I'll have one of my other bots keep an eye on it and restart it whenever it goes down. Sorry for the problem!

**Comment by Aida-Enna** [comment] 2020-12-30 01:38
So the reason that the bot started crashing hard a bit ago is because the Discord library needs to updated, along with some code changes to accomidate that. I'll post again (and close this issue) once I'm done and the bot is working again.

**Comment by enternius** [comment] 2020-12-30 01:40
Thanks a ton, was trying to get it set back up when I noticed it wasn't responding to my commands and got a bit nervous.

No rush though, I appreciate that you're doing it either way

**Comment by Aida-Enna** [comment] 2020-12-30 02:31
Discord code fixed, bot is operational and working as intended! I'll keep the server monitoring code up just in case. If the bot goes down again and is down for more than an hour, please make an issue here. If I don't respond within 12 hours (Github please please PLEASE send me the notifications, I have this repo on "Watch All Activity"!), please send me a DM on Discord (Aida Enna#0001) so I can fix it. Sorry, and thank you everyone for your patience 🙏

**Closed by Aida-Enna** 2020-12-30 02:31 UTC
